version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=cool_db
      - POSTGRES_USER=zero_example
      - POSTGRES_PASSWORD=requiem_example
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin123@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DB=mysql_store
      - MYSQL_USER=diah
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
